Update README to explain how LocalLLMAttributor and APILLMAttributor …
leap-laboratories/llm-attribution pull request #5
Opened 2024-06-03 17:35 UTC by sebastian-sosa

…classes work

2024-06-05 16:25 UTC, jessicarumbelow requested changes
Could we add two quickstart snippets with example outputs to the top of the readme, one for GPT and one for an os model?

2024-06-11 16:34 UTC, atagade commented on research/llm_attribution_metric.ipynb
> +    "__NOTE__: We also print out the logging table for each input string to ensure that the output strings are what we expect and our predefined output ids are valid."
Done

2024-06-11 16:34 UTC, atagade commented on README.md
Done by Seba

2024-06-11 16:35 UTC, atagade approved these changes

2024-06-13 15:37 UTC, jessicarumbelow approved these changes

2024-06-13 15:37 UTC, merged